services:
  frontend:
    build:
      context: ./frontend # The local path to the frontend source code
    container_name: vinyl-frontend
    volumes:
      - ./frontend:/app # Mounts the entire local frontend directory as `/app` in the container
      - /app/node_modules # Prevents the node_modules directory from being overridden by the container
        # (avoid conflicts between the dependencies installed on the host machine and those installed inside the container)
      - ./database/sample_data/images:/app/media # Shared volume for album art and other media files
    environment:
      # Variables that can be accessed in the frontend application
      - REACT_APP_API_BASE_URL # `/api`
      - CHOKIDAR_INTERVAL=100
      - CHOKIDAR_USEPOLLING # File change detection for reload
      - WDS_SOCKET_PORT=0 # Use the default Webpack Dev Server socket port (needed for hot reloading)
    env_file:
      - .env # `environment` pulls from this file in the root directory of this folder
    depends_on:
      - backend # Only startup after the backend service is up
    networks:
      - vinyl-network # Putting all services in the same network for inter-container communication

  # Local backend changes are automatically reflected in the container upon saving
  # (Exception: changes to the Dockerfile require a rebuild)
  backend:
    build:
      context: ./backend
    container_name: vinyl-backend
    volumes:
      - ./backend:/app
      - ./database/sample_data/images:/media
      - ./database/sample_data/import-albums.csv:/app/import-albums.csv
      - ./database/sample_data/import-songs.csv:/app/import-songs.csv
      - ./debugging_imgs:/app/debugging_imgs
    environment:
      - DATABASE_URL
      - REDIS_URL
      - MEDIA_DIR
    env_file:
      - .env
    depends_on:
      database:
        # Ensure the database container starts before the backend
        condition: service_healthy
      cache:
        condition: service_healthy # Ensure the Redis cache container starts before the backend
    networks:
      - vinyl-network

  # If renaming this service, update DATABASE_URL in the .env file!
  database:
    image: postgres:15
    container_name: vinyl-database
    build:
      context: ./database # Tell Docker to build the database service from the Dockerfile in the database directory
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for the database data (allows data to outlive container restarts/builds)
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize the database with our custom SQL init script
      - ./database/sample_data/images:/media
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vinyl_db
    env_file:
      - .env
    networks:
      - vinyl-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro # Mount the pre-configured servers.json file
    depends_on:
      database:
        # Ensure the database container starts before pgAdmin
        condition: service_healthy
    networks:
      - vinyl-network

  # If renaming this service, update REDIS_URL in the .env file
  cache:
    image: redis:7
    container_name: vinyl-cache
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - vinyl-network

  nginx:
    image: nginx:latest # Use the official Nginx image.
    container_name: vinyl-nginx
    ports:
      - "80:80" # Default (http) web port
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro # Mount the built folder of the frontend app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Bind mount the config file. 'ro' ensures read-only access meaning the container can't modify the file on the host
      - ./nginx/favicon.ico:/etc/nginx/favicon.ico:ro # Bind mount the favicon
      - ./database/sample_data/images:/media:ro
    depends_on:
      - frontend
      - backend
      - database
      - cache
    networks:
      - vinyl-network

volumes:
  postgres_data: # Define a persistent volume for the PostgreSQL database (to outlive container restarts)
  redis_data: # Persistent volume for the Redis cache

networks:
  vinyl-network:
    # Define a custom network for inter-container communication
