services:
  frontend:
    build:
      context: ./frontend # The local path to the frontend source code
    container_name: vinyl-frontend
    volumes:
      - ./frontend:/app # Mounts the local frontend directory into the container for development (real-time changes)
    environment:
      # Variables that can be accessed in the frontend application
      - REACT_APP_API_BASE_URL
      - CHOKIDAR_USEPOLLING
    env_file:
      - .env
    networks:
      - vinyl-network # Putting all services in the same network for inter-container communication

  backend:
    build:
      context: ./backend
    container_name: vinyl-backend
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL
      - REDIS_URL
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - database # Ensure the database container starts before the backend
      - cache # Ensure the Redis cache container starts before the backend
    networks:
      - vinyl-network

  database:
    build:
      context: ./database
    container_name: vinyl-database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for the database data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize the database with a custom SQL script
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=trust # Don't want to use a password
    env_file:
      - .env
    networks:
      - vinyl-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    env_file:
      - .env
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro # Mount the pre-configured servers.json file
    depends_on:
      - database # Ensure the database container starts before pgAdmin
    networks:
      - vinyl-network

  cache:
    image: redis:7
    container_name: vinyl-cache
    volumes:
      - redis_data:/data
    networks:
      - vinyl-network

  vector-search:
    build:
      context: ./vector-search
    container_name: vinyl-vector-search
    environment:
      - DATABASE_URL
    env_file:
      - .env
    depends_on:
      - database # FYI - doesn't guarantee that the database is ready
    networks:
      - vinyl-network

  nginx:
    image: nginx:latest # Use the official Nginx image.
    container_name: vinyl-nginx
    ports:
      - "80:80" # Default (http) web port
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro # Mount the build folder
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Bind mount the config file. 'ro' ensures read-only access meaning the container can't modify the file on the host
      - ./nginx/favicon.ico:/etc/nginx/favicon.ico:ro # Bind mount the favicon
    depends_on:
      - frontend
      - backend
    networks:
      - vinyl-network

volumes:
  postgres_data: # Define a persistent volume for the PostgreSQL database (to outlive container restarts)
  redis_data:
    # Define a persistent volume for the Redis cache

networks:
  vinyl-network:
    # Define a custom network for inter-container communication
    driver: bridge # Use the bridge network driver for isolation
